### PR TITLE
Revise S./T. Chinese language

### PR DESCRIPTION
**Pull request by CaiMiao**
big revise in human phrase

### CODE REVIEW

**Comment by WanderMax** [comment]
zh-CN and zh-TW are better in language code, following ISO 639-1.
For translation in detail, I will review it when I'm free.
@Polytoo

**Comment by CaiMiao** [comment]
> zh-CN and zh-TW are better in language code

FYI, HOS now use `zh-Hans` and `zh-Hant` as `LanguageCode`.
See https://switchbrew.org/wiki/Settings_services#Language .

**Comment by CaiMiao** [comment]
latest push includes an alias for language code to further improve libnx compliance while keeping compatibility with older settings

**Comment by CaiMiao** [comment]
fix few TC term:

固件->韌體

輸入->鍵入

**Comment by WanderMax** [comment]
@CaiMiao I compare your translation with the current one:
1. I think the LanguageCode revision you mentioned maybe a little better for matching HOS;
2. the current simplified Chinese translation is OK enough, as it's revised by me and @Polytoo ;
3. for traditional Chinese translation, you can ask Polytoo, the owner of first traditional Chinese translation PR

**Comment by CaiMiao** [comment]
I spent efforts of an afternoon plus some remind time for revising terms to be "correct" instead of "just OK",  
but if you really want to insist you were "OK enough" and denying any suggestion then I have nothing to say.

For TC, the old one were more of a simple S->T conversion instead of correcting mainland glossaries to HK/TW one, leads to a really low quality result.

**Comment by WanderMax** [comment]
@CaiMiao **suggestion is warmly welcomed!** sorry for that.
I know the time you spent in translation, as we have done the same thing. in fact, I translate the strings, run the binary file Polytoo compiled, then again if not that suitable.
for TC, you are right I think.

**Comment by impeeza** [comment]
> I spent efforts of an afternoon plus some remind time for revising terms to be "correct" instead of "just OK",
> but if you really want to insist you were "OK enough" and denying any suggestion then I have nothing to say.
> 
> For TC, the old one were more of a simple S->T conversion instead of correcting mainland glossaries to HK/TW one, leads to a really low quality result.

Do not waste your time trying to colaborate in this app you only will reveive responses like:

«I'm willing to settle with something that's at least legible for now, it would be more work than I'd like to do currently to account for this sort of thing. Let me know if it's in a state you're happy with and I can accept this.»

Do not worth your time

**Comment by HookedBehemoth** [comment]
Let me know if it's in a state you're happy with and I can accept this.

**Comment by CaiMiao** [comment]
> Let me know if it's in a state you're happy with and I can accept this.

Amusing though. @WanderMax Let me know if it's in a state you're happy with and they can accept this.

[Awoo-Installer.zip](https://github.com/Huntereb/Awoo-Installer/files/5898124/Awoo-Installer.zip)

**Comment by WanderMax** [comment]
Let us move forward, **your translation is correct**. There is no need to quarreling about translation style difference.
You can be in charge of it.
The end.

**Comment by CaiMiao** [comment]
> There is no need to quarreling about translation style difference.

I looked forward to further suggestion if you have any, but... alright, I am generally okay to whatever.  
But I have to say, whenever I say *correct*, that would be in terms of *accuracy* instead of a simple true or false. I must admit your work was generally good, but it could be better in details and so I came. And it would not have extra work for you all.

**Comment by Polytoo** [comment]
Hi guys, Sorry for the late reply.
@CaiMiao @WanderMax @HookedBehemoth 
We translated the TC version directly from SC version. 
@CaiMiao 's TC version may be better for HK and TW users.
But, some parts of the text should keep the original meaning. 
Keeps "XCI" is much better than translates it to  "从卡带转换" (line:106). 

For the code part, "zh-Hans" and "zh-Hant" file names are follow most of the game's style (Like: The Elder Scrolls V).
I don't suggest to delete and add files, it will breakdown the revision of the translation text.

Appreciate your effort on the TC translation work. Hope we can work together and make the TC version better.
Actually, I have been waiting someone to polish the TC version for a long time. 

 :)

**Comment by Huntereb** [comment]
I just noticed this was committed to the dev branch lol... I'll have to manually merge it later I guess.

**Pull request merged**
