### PR TITLE
Chinese simplified translation initiate

### PR DESCRIPTION
**Pull request by WanderMax**
some desc strings may have dialogue box width issue(I don't know dialogue width limit for string).
translation can use system font to display strings.
need .nro file to fix dialogue box width issue as I have no machine to compile, sorry~

### CODE REVIEW

**Comment by Huntereb** [comment]
I just went over this in #40 . I'll keep this around, but unfortunately I can't accept it without doing some work to the way system fonts are loaded.

**Comment by HookedBehemoth** [comment]
Also at least some of the characters you used aren't formated in UTF-8 so we can't read them.

**Comment by WanderMax** [comment]
Could you please tell me how to set utf8 coding in web-flow? or I need to format strings into '\u' type? I can make one new commit. Thanks.

**Comment by Polytoo** [comment]
Oh, I think I had been doing the same thing......
I've just finished the translation and code modification. I am testing for ensuring the code safty.
After that, I would like to post a PR.

**Comment by HookedBehemoth** [comment]
I'm sorry for letting your work go to waste and me even giving you wrong advice.
We've decided on accepting Polytoo's pull request as it also directly addressed the font issue we faced and also added simplified chinese.

I hope you don't get discouraged from contributing to this or other open source projects in the future.

**Pull request closed without merging**
