### PR TITLE
Add Spanish (from Spain) translation

### PR DESCRIPTION
**Pull request by PabloPerezRodriguez**
Title.

I would love it if somebody could error check it.

### CODE REVIEW

**Comment by HookedBehemoth** [comment]
Can this be used for ES419/LatinAmericanSpanish too?

**Comment by impeeza** [comment]
No. For Latinamerican spanish I have crwated the issue
https://github.com/Huntereb/Awoo-Installer/issues/95
Asking to add these lenguaje. I was unable to create a commit request

**Comment by PabloPerezRodriguez** [comment]
It should. It may just seem a little bit weird at times for people who speak Latin American Spanish, but still very understandable for them.

**Comment by impeeza** [comment]
It's just like the difference between UK and US English.  Are the same language but differents sayings, modisms and terms.

**Comment by PabloPerezRodriguez** [comment]
Exactly

**Comment by Huntereb** [comment]
I'm willing to settle with something that's at least legible for now, it would be more work than I'd like to do currently to account for this sort of thing. Let me know if it's in a state you're happy with and I can accept this.

**Comment by Huntereb** [comment]
I'm willing to settle with something that's at least legible for now, it would be more work than I'd like to do currently to account for this sort of thing. Let me know if it's in a state you're happy with and I can accept this.

**Comment by PabloPerezRodriguez** [comment]
The only thing I'm worried about is if newlines are placed correctly. If they are, everything else looks ok

**Comment by Huntereb** [comment]
Sorry, was busy. Gotcha.

**Pull request merged**
