### PR TITLE
Chinese Simplified translation fix

### PR DESCRIPTION
**Pull request by WanderMax**
I do some Chinese Simplified translation fix for Polytoo's PR

### CODE REVIEW

**Comment by WanderMax** [comment]
@Polytoo we can cooperate for this translation fix

**Comment by Polytoo** [comment]
@WanderMax Thank you for your polished translation text. 
I see most parts of your translation are better, but some small pars need to fix.
For example:
`
        "cancel_desc": "按 \ue0e1 取消"
`
`
        "cancel_desc": "按 B 以取消"
`
I tend to use Nintendo magic code to present the button than a 'B' character.

I also have recived your message, we can discuss and fix it together.

**Comment by WanderMax** [comment]
@Polytoo change button string to Nintendo magic code, please check again.

**Comment by Polytoo** [comment]
@WanderMax I have sent my merged version to you via QQ.
Please check it.

Thank you!

**Comment by WanderMax** [comment]
@Huntereb @Polytoo Chinese Simplified translation fix is done.

**Comment by Polytoo** [comment]
@WanderMax Thank you for contributing. I have built and run it without any problem.
@Huntereb The tanslation text has been polished, I think it better than the initial one, could you please check and merge it?

Thank you!

**Pull request merged**
